services:
  mysql_db:
    image: mysql:8.0.31
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./server/database:/docker-entrypoint-initdb.d
      - $HOME/mysql_db:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_db
    networks:
      internalnet:
        ipv4_address: 10.5.0.5
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 8s
      retries: 5

  node_server:
    container_name: nodeservercontainer
    build: ./server
    image: nodeserver:v1
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    environment:
      DB_HOST: mysql_db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}
      SERVICE_TAGS: dev
      SERVICE_NAME: node_server
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      internalnet:
        ipv4_address: 10.5.0.6

  client:
    container_name: reactappcontainer
    build: ./client
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    depends_on:
      - node_server
    networks:
      internalnet:
        ipv4_address: 10.5.0.7

networks:
  internalnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1