services:
  mysql_db:
    image: mysql:8.0.31
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./server/database:/docker-entrypoint-initdb.d
      - $HOME/mysql_db:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  node_server:
    container_name: nodeservercontainer
    build: .
    image: nodeserver:v1
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    environment:
      DB_HOST: mysqldb
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeserverservice
    depends_on:
      - mysql_db
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge